### ISSUE TITLE
how to use it ?

### ISSUE THREAD

**Issue by cloudjanak** [KhaosT/ANCS-Mac#1]

**Comment by BluePick** [comment]
+1

**Comment by KhaosT** [comment]
This project no longer works on macOS due to Core Bluetooth filtering out ANCS related services.

**Comment by BluePick** [comment]
I observe there some app which provides this features...

**Comment by KhaosT** [comment]
Can you tell which app can do that on Mac? Last time I check ANCS service
is filtered already.

**Comment by BluePick** [comment]
http://www.getnotifyr.com/

**Comment by KhaosT** [comment]
``You'll need Mavericks or Yosemite to receive iOS notifications and run Notifyr.`` I think Apple filtered those services after that... Were you able to get Notifyr work with Sierra?

**Comment by BluePick** [comment]
I think app not working on Sierra.

**Comment by raisen** [comment]
I read it's possible to connect to ANCS from a Mac using a USB Bluetooth dongle and run the scan through a virtual machine.
Just checking if there is still no workaround for CoreBluetooth to connect to ANCS, correct?
